resources:
  repositories:
    - repository: efm-eproc-pipeline
      type: github
      name: felleslosninger/efm-eproc-pipeline
      endpoint: felleslosninger
      ref: feature-dockerhub_push

extends:
  template: build-and-deploy-template.yml@efm-eproc-pipeline
  parameters:
    environmentRepository: git://eformidling/eformidling
    jdkVersion: 1.8
    buildDockerArtifact: false
    dockerhubPush: true
    dockerhubRepo: difi/integrasjonspunkt
    dockerfile: integrasjonspunkt/Dockerfile
    coverageTool: none

trigger:
  batch: true
  branches:
    include:
      - development
      - release-*
      - master