resources:
  repositories:
    - repository: efm-eproc-pipeline
      type: github
      name: felleslosninger/efm-eproc-pipeline
      endpoint: felleslosninger

extends:
  template: build-and-deploy-template.yml@efm-eproc-pipeline
  parameters:
    includeDatetimeInTag: false
    environmentRepository: git://eformidling/eformidling
    jdkVersion: 1.8

trigger:
  batch: true
  branches:
    include:
      - development
      - release-*
      - master
