resources:
  repositories:
    - repository: efm-eproc-pipeline
      type: github
      name: felleslosninger/efm-eproc-pipeline
      endpoint: felleslosninger
      ref: feature-MOVE-2212_ossrh

extends:
  template: build-and-deploy-template.yml@efm-eproc-pipeline
  parameters:
    environmentRepository: git://eformidling/eformidling
    jdkVersion: 1.8
    coverageTool: none
    buildDockerArtifact: false
    dockerhubPush: false
    dockerRegistryEndpoint: dockerhub-difi
    deployOssrh: true
    mavenGoals: deploy

trigger:
  batch: true
  branches:
    include:
      - development
      - release-*
      - master
