server:
  port: 8090
spring:
  application:
    name: Spring-Boot-Monitor-UI-Localhost
  cloud:
    config:
      enabled: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---

spring:
    profiles: docker
    application:
      name: Spring-Boot-Monitor-UI-Docker
    cloud:
      config:
        enabled: false
server:
  port: 8090
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
